In [3]:
import pandas as pd

In [6]:
import pandas as pd

rolls = pd.read_csv(
    "data/processed/roll_calls/roll_call_stats_119.csv"
)

members = pd.read_csv(
    "data/processed/members/member_vote_alignment_119.csv"
)

print(f"Roll calls:   {len(rolls):,}")
print(f"Member votes: {len(members):,}")
print(f"Members:      {members['bioguide_id'].nunique():,}")

Roll calls:   676
Member votes: 292,248
Members:      452

In [7]:
roll_view = rolls[
    [
        "session",
        "roll_number",
        "action_date",
        "legislation_number",
        "vote_question",
        "vote_description",
        "house_yea",
        "house_nay",
        "house_present",
        "house_not_voting",
        "republican_position",
        "republican_majority_strength",
        "democratic_position",
        "democratic_majority_strength",
        "parties_opposed",
    ]
].copy()

roll_view

,session,roll_number,action_date,legislation_number,vote_question,vote_description,house_yea,house_nay,house_present,house_not_voting,republican_position,republican_majority_strength,democratic_position,democratic_majority_strength,parties_opposed
0,1st,1,3-Jan-2025,QUORUM,Call by States,NaN,0,0,433,2,No Position,NaN,No Position,NaN,False
1,1st,2,3-Jan-2025,NaN,Election of the Speaker,NaN,0,0,0,0,NaN,NaN,NaN,NaN,False
2,1st,3,3-Jan-2025,H RES 5,On Ordering the Previous Question,Adopting the Rules of the House of Representat...,216,210,0,8,Yea,1.000000,Nay,1.000000,True
3,1st,4,3-Jan-2025,H RES 5,On Motion to Commit with Instructions,Adopting the Rules of the House of Representat...,209,214,0,11,Nay,1.000000,Yea,1.000000,True
4,1st,5,3-Jan-2025,H RES 5,On Agreeing to the Resolution,Adopting the Rules of the House of Representat...,215,209,0,10,Yea,1.000000,Nay,0.995238,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,2nd,310,16-Sep-2026,H R 10326,On Passage,PROOF Act,217,207,0,9,Yea,0.995261,Nay,0.971698,True
672,2nd,311,16-Sep-2026,H J RES 213,On Passage,Providing for congressional disapproval under ...,214,208,0,11,Yea,0.995261,Nay,0.985714,True
673,2nd,312,16-Sep-2026,H R 9340,"On Motion to Suspend the Rules and Pass, as Am...",Ratepayer Protection Act,417,3,0,12,Yea,1.000000,Yea,0.985646,False
674,2nd,313,16-Sep-2026,H R 9497,"On Motion to Suspend the Rules and Pass, as Am...",Water Resources Development Act,415,9,0,9,Yea,0.957346,Yea,1.000000,False
675,2nd,314,16-Sep-2026,S 2403,On Motion to Suspend the Rules and Pass,Retire through Ownership Act,401,14,0,18,Yea,0.931707,Yea,1.000000,False

In [8]:
members.columns.tolist()

['congress',
 'session',
 'roll_number',
 'bioguide_id',
 'representative',
 'party',
 'party_code',
 'state',
 'role',
 'vote',
 'source_file',
 'validation_type',
 'vote_question',
 'vote_description',
 'legislation_number',
 'action_date',
 'vote_result',
 'house_yea',
 'house_nay',
 'house_present',
 'house_not_voting',
 'house_yea_share_of_yea_nay',
 'house_nay_share_of_yea_nay',
 'republican_position',
 'democratic_position',
 'republican_majority_strength',
 'democratic_majority_strength',
 'parties_opposed',
 'parties_same_side',
 'major_party_yea_share_difference',
 'own_party_position',
 'other_major_party_position',
 'own_party_majority_strength',
 'alignment',
 'cast_yea_or_nay',
 'cast_any_vote',
 'is_major_party_member',
 'against_party_when_parties_opposed',
 'against_party_when_parties_same_side']

In [9]:
fitz = members[
    members["representative"]
    .str.contains("Fitzpatrick", case=False, na=False)
].copy()

print(f"Rows: {len(fitz):,}")
print()
print(
    fitz[
        ["bioguide_id", "representative", "party", "state"]
    ]
    .drop_duplicates()
    .to_string(index=False)
)

Rows: 676

bioguide_id representative      party state
    F000466    Fitzpatrick Republican    PA

In [10]:
fitz["alignment"].value_counts()

alignment
with_own_party       559
against_own_party    108
not_voting             6
present_or_other       2
nonstandard_roll       1
Name: count, dtype: int64

In [11]:
check_special = fitz[
    fitz["alignment"].isin([
        "not_voting",
        "present_or_other",
        "nonstandard_roll",
    ])
][[
    "session",
    "roll_number",
    "action_date",
    "legislation_number",
    "vote_question",
    "vote_description",
    "vote",
    "alignment",
    "validation_type",
    "house_yea",
    "house_nay",
    "house_present",
    "house_not_voting",
]]

check_special

,session,roll_number,action_date,legislation_number,vote_question,vote_description,vote,alignment,validation_type,house_yea,house_nay,house_present,house_not_voting
122,1st,1,3-Jan-2025,QUORUM,Call by States,NaN,Present,present_or_other,party_totals,0,0,433,2
557,1st,2,3-Jan-2025,NaN,Election of the Speaker,NaN,Johnson (LA),nonstandard_roll,candidate_totals,0,0,0,0
8362,1st,20,22-Jan-2025,H RES 53,On Ordering the Previous Question,Providing for consideration of the bill (H.R. ...,Not Voting,not_voting,party_totals,214,204,0,15
8795,1st,21,22-Jan-2025,H RES 53,On Agreeing to the Resolution,Providing for consideration of the bill (H.R. ...,Not Voting,not_voting,party_totals,213,204,0,16
37337,1st,87,1-Apr-2025,H RES 282,On Agreeing to the Resolution,Providing for consideration of the joint resol...,Not Voting,not_voting,party_totals,206,222,0,3
55077,1st,128,14-May-2025,H R 2243,On Passage,LEOSA Reform Act,Not Voting,not_voting,party_totals,229,193,0,11
148158,1st,343,17-Dec-2025,H RES 953,On Ordering the Previous Question,Providing for consideration of the bills (H.R....,Not Voting,not_voting,party_totals,204,203,0,26
156834,2nd,1,6-Jan-2026,QUORUM,Call of the House,NaN,Present,present_or_other,party_totals,0,0,406,24
255994,2nd,231,30-Jun-2026,H RES 1398,On Agreeing to the Resolution,Providing for consideration of the bills H.R. ...,Not Voting,not_voting,party_totals,198,224,0,9

In [13]:
check_special.roll_number.to_list()

[1, 2, 20, 21, 87, 128, 343, 1, 231]

In [14]:
fitz[
    fitz["alignment"] == "present_or_other"
][[
    "session",
    "roll_number",
    "action_date",
    "vote_question",
    "vote_description",
    "vote",
    "own_party_position",
    "republican_position",
    "democratic_position",
    "house_yea",
    "house_nay",
    "house_present",
    "house_not_voting",
]]

,session,roll_number,action_date,vote_question,vote_description,vote,own_party_position,republican_position,democratic_position,house_yea,house_nay,house_present,house_not_voting
122,1st,1,3-Jan-2025,Call by States,NaN,Present,No Position,No Position,No Position,0,0,433,2
156834,2nd,1,6-Jan-2026,Call of the House,NaN,Present,No Position,No Position,No Position,0,0,406,24

In [15]:
fitz[
    fitz["alignment"] == "nonstandard_roll"
][[
    "session",
    "roll_number",
    "action_date",
    "vote_question",
    "vote",
    "validation_type",
]]

,session,roll_number,action_date,vote_question,vote,validation_type
557,1st,2,3-Jan-2025,Election of the Speaker,Johnson (LA),candidate_totals

In [16]:
fitz_breaks = fitz[
    fitz["alignment"] == "against_own_party"
][[
    "session",
    "roll_number",
    "action_date",
    "legislation_number",
    "vote_question",
    "vote_description",
    "vote",
    "own_party_position",
    "own_party_majority_strength",
    "democratic_position",
    "parties_opposed",
    "house_yea",
    "house_nay",
]].copy()

fitz_breaks

,session,roll_number,action_date,legislation_number,vote_question,vote_description,vote,own_party_position,own_party_majority_strength,democratic_position,parties_opposed,house_yea,house_nay
17452,1st,41,12-Feb-2025,H R 77,On Passage,Midnight Rules Relief Act,Nay,Yea,0.995283,Nay,True,212,208
22212,1st,52,26-Feb-2025,H J RES 35,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995349,Nay,True,220,206
24809,1st,58,5-Mar-2025,H J RES 61,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995238,Nay,True,216,202
26105,1st,61,6-Mar-2025,S J RES 11,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995305,Nay,True,221,202
47720,1st,111,30-Apr-2025,H J RES 87,On Passage,"Congressional disapproval, of the rule submitt...",Nay,Yea,0.995434,Nay,True,231,191
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278100,2nd,282,23-Jul-2026,H CON RES 89,On Agreeing to the Resolution,"Directing the President, pursuant to section 5...",Yea,Nay,0.981043,Yea,True,214,208
281983,2nd,291,1-Sep-2026,H R 9436,On Passage,"To amend the Consolidated Appropriations Act, ...",Nay,Yea,0.990521,Nay,True,219,196
288473,2nd,306,15-Sep-2026,H J RES 210,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995305,Nay,True,216,211
288906,2nd,307,15-Sep-2026,H CON RES 93,On Agreeing to the Resolution,"Directing the President, pursuant to section 5...",Yea,Nay,0.966667,Yea,True,220,204
290638,2nd,311,16-Sep-2026,H J RES 213,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995261,Nay,True,214,208

In [17]:
opposed_breaks = fitz_breaks[
    fitz_breaks["parties_opposed"]
].head(5)

same_side_breaks = fitz_breaks[
    ~fitz_breaks["parties_opposed"]
].head(5)

display(opposed_breaks)
display(same_side_breaks)

,session,roll_number,action_date,legislation_number,vote_question,vote_description,vote,own_party_position,own_party_majority_strength,democratic_position,parties_opposed,house_yea,house_nay
17452,1st,41,12-Feb-2025,H R 77,On Passage,Midnight Rules Relief Act,Nay,Yea,0.995283,Nay,True,212,208
22212,1st,52,26-Feb-2025,H J RES 35,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995349,Nay,True,220,206
24809,1st,58,5-Mar-2025,H J RES 61,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995238,Nay,True,216,202
26105,1st,61,6-Mar-2025,S J RES 11,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995305,Nay,True,221,202
47720,1st,111,30-Apr-2025,H J RES 87,On Passage,"Congressional disapproval, of the rule submitt...",Nay,Yea,0.995434,Nay,True,231,191

,session,roll_number,action_date,legislation_number,vote_question,vote_description,vote,own_party_position,own_party_majority_strength,democratic_position,parties_opposed,house_yea,house_nay
192227,2nd,83,4-Mar-2026,H RES 1100,On Motion to Refer,Directing the Committee on Ethics to preserve ...,Nay,Yea,0.821596,Yea,False,357,65

In [18]:
fitz_opposed_breaks = fitz[
    (fitz["alignment"] == "against_own_party") &
    (fitz["parties_opposed"] == True)
].copy()

print(f"Against own party, all votes: {len(fitz[fitz['alignment'] == 'against_own_party']):,}")
print(f"Against own party when parties opposed: {len(fitz_opposed_breaks):,}")

fitz_opposed_breaks[[
    "session",
    "roll_number",
    "action_date",
    "legislation_number",
    "vote_question",
    "vote_description",
    "vote",
    "own_party_position",
    "own_party_majority_strength",
    "democratic_position",
    "house_yea",
    "house_nay",
]]

Against own party, all votes: 108
Against own party when parties opposed: 107

,session,roll_number,action_date,legislation_number,vote_question,vote_description,vote,own_party_position,own_party_majority_strength,democratic_position,house_yea,house_nay
17452,1st,41,12-Feb-2025,H R 77,On Passage,Midnight Rules Relief Act,Nay,Yea,0.995283,Nay,212,208
22212,1st,52,26-Feb-2025,H J RES 35,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995349,Nay,220,206
24809,1st,58,5-Mar-2025,H J RES 61,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995238,Nay,216,202
26105,1st,61,6-Mar-2025,S J RES 11,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995305,Nay,221,202
47720,1st,111,30-Apr-2025,H J RES 87,On Passage,"Congressional disapproval, of the rule submitt...",Nay,Yea,0.995434,Nay,231,191
...,...,...,...,...,...,...,...,...,...,...,...,...
278100,2nd,282,23-Jul-2026,H CON RES 89,On Agreeing to the Resolution,"Directing the President, pursuant to section 5...",Yea,Nay,0.981043,Yea,214,208
281983,2nd,291,1-Sep-2026,H R 9436,On Passage,"To amend the Consolidated Appropriations Act, ...",Nay,Yea,0.990521,Nay,219,196
288473,2nd,306,15-Sep-2026,H J RES 210,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995305,Nay,216,211
288906,2nd,307,15-Sep-2026,H CON RES 93,On Agreeing to the Resolution,"Directing the President, pursuant to section 5...",Yea,Nay,0.966667,Yea,220,204
290638,2nd,311,16-Sep-2026,H J RES 213,On Passage,Providing for congressional disapproval under ...,Nay,Yea,0.995261,Nay,214,208

In [19]:
fitz_opposed = fitz[
    fitz["parties_opposed"] == True
].copy()

print(f"Total party-opposed roll calls: {len(fitz_opposed):,}")
print()
print("Fitzpatrick's behavior:")
print(fitz_opposed["alignment"].value_counts())

print()
print("Percent of party-opposed roll calls:")
print(
    (fitz_opposed["alignment"].value_counts(normalize=True) * 100)
    .round(2)
)

Total party-opposed roll calls: 471

Fitzpatrick's behavior:
alignment
with_own_party       358
against_own_party    107
not_voting             6
Name: count, dtype: int64

Percent of party-opposed roll calls:
alignment
with_own_party       76.01
against_own_party    22.72
not_voting            1.27
Name: proportion, dtype: float64

In [20]:
eligible = len(fitz_opposed)

not_voting = (fitz_opposed["alignment"] == "not_voting").sum()
present_other = (fitz_opposed["alignment"] == "present_or_other").sum()
votes_cast = fitz_opposed["cast_yea_or_nay"].sum()

with_party = (fitz_opposed["alignment"] == "with_own_party").sum()
against_party = (fitz_opposed["alignment"] == "against_own_party").sum()

print(f"Eligible party-opposed votes: {eligible:,}")
print(f"Yea/Nay votes cast:          {votes_cast:,}")
print(f"Not voting:                  {not_voting:,}")
print(f"Present/other:               {present_other:,}")
print()
print(f"With own party:              {with_party:,}")
print(f"Against own party:           {against_party:,}")
print()
print(f"Participation rate:          {votes_cast / eligible:.1%}")
print(f"Against-party rate cast:     {against_party / votes_cast:.1%}")
print(f"Against-party share eligible:{against_party / eligible:.1%}")

Eligible party-opposed votes: 471
Yea/Nay votes cast:          465
Not voting:                  6
Present/other:               0

With own party:              358
Against own party:           107

Participation rate:          98.7%
Against-party rate cast:     23.0%
Against-party share eligible:22.7%

In [22]:
thresholds = [.50, .55, .60, .65, .70, .75, .80, .85, .90, .95]

rows = []

opposed_rolls = rolls[rolls["parties_opposed"] == True].copy()

for threshold in thresholds:
    count = (
        (opposed_rolls["republican_majority_strength"] >= threshold) &
        (opposed_rolls["democratic_majority_strength"] >= threshold)
    ).sum()

    rows.append({
        "minimum_party_agreement": f"{threshold:.0%}",
        "roll_calls": count,
        "share_of_471": count / len(opposed_rolls)
    })

strength_table = pd.DataFrame(rows)
strength_table["share_of_471"] = strength_table["share_of_471"].map(
    lambda x: f"{x:.1%}"
)

strength_table

  minimum_party_agreement  roll_calls share_of_471
0                     50%         471       100.0%
1                     55%         465        98.7%
2                     60%         457        97.0%
3                     65%         446        94.7%
4                     70%         444        94.3%
5                     75%         435        92.4%
6                     80%         428        90.9%
7                     85%         414        87.9%
8                     90%         391        83.0%
9                     95%         353        74.9%

In [23]:
opposed_rolls = rolls[rolls["parties_opposed"] == True].copy()

opposed_rolls["weaker_party_strength"] = opposed_rolls[
    ["republican_majority_strength", "democratic_majority_strength"]
].min(axis=1)

weakest = opposed_rolls.sort_values(
    "weaker_party_strength"
)[[
    "session",
    "roll_number",
    "action_date",
    "legislation_number",
    "vote_question",
    "vote_description",
    "house_yea",
    "house_nay",
    "republican_yea",
    "republican_nay",
    "republican_position",
    "republican_majority_strength",
    "democratic_yea",
    "democratic_nay",
    "democratic_position",
    "democratic_majority_strength",
    "weaker_party_strength",
]].head(30)

weakest

,session,roll_number,action_date,legislation_number,vote_question,vote_description,house_yea,house_nay,republican_yea,republican_nay,republican_position,republican_majority_strength,democratic_yea,democratic_nay,democratic_position,democratic_majority_strength,weaker_party_strength
604,2nd,243,15-Jul-2026,H R 8595,On Agreeing to the Amendment,NaN,104,314,1,215,Nay,0.995370,103,98,Yea,0.512438,0.512438
199,1st,200,17-Jul-2025,S 1582,On Passage,GENIUS Act,308,122,206,12,Yea,0.944954,102,110,Nay,0.518868,0.518868
32,1st,33,6-Feb-2025,H R 27,On Passage,HALT Fentanyl Act,312,108,214,1,Yea,0.995349,98,107,Nay,0.521951,0.521951
304,1st,305,21-Nov-2025,H CON RES 58,On Agreeing to the Resolution,Denouncing the horrors of socialism,285,98,199,0,Yea,1.000000,86,98,Nay,0.532609,0.532609
532,2nd,171,14-May-2026,H R 5625,On Passage,Cashless Bail Reporting Act,308,116,211,2,Yea,0.990610,96,114,Nay,0.542857,0.542857
525,2nd,164,13-May-2026,H R 1346,On Passage,Nationwide Consumer and Fuel Retailer Choice Act,218,203,122,90,Yea,0.575472,95,113,Nay,0.543269,0.543269
233,1st,234,3-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,120,307,120,96,Yea,0.555556,0,211,Nay,1.000000,0.555556
230,1st,231,3-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,120,306,120,96,Yea,0.555556,0,210,Nay,1.000000,0.555556
234,1st,235,4-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,120,302,120,95,Yea,0.558140,0,207,Nay,1.000000,0.558140
231,1st,232,3-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,124,303,124,92,Yea,0.574074,0,211,Nay,1.000000,0.574074
619,2nd,258,21-Jul-2026,H R 8800,On Agreeing to the Amendment,NaN,265,161,90,123,Nay,0.577465,175,37,Yea,0.825472,0.577465
327,1st,328,11-Dec-2025,H R 3383,On Passage,Increasing Investor Opportunities Act,302,123,215,0,Yea,1.000000,87,123,Nay,0.585714,0.585714
235,1st,236,4-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,127,297,127,88,Yea,0.590698,0,209,Nay,1.000000,0.590698
232,1st,233,3-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,127,299,127,88,Yea,0.590698,0,211,Nay,1.000000,0.590698
157,1st,158,9-Jun-2025,H RES 488,On Motion to Suspend the Rules and Agree,Denouncing the antisemitic terrorist attack in...,280,113,205,0,Yea,1.000000,75,113,Nay,0.601064,0.601064
67,1st,68,11-Mar-2025,H R 1156,On Passage,Pandemic Unemployment Fraud Enforcement Act,295,127,212,0,Yea,1.000000,83,127,Nay,0.604762,0.604762
388,2nd,27,14-Jan-2026,H R 7006,On Agreeing to the Amendment,NaN,127,291,127,81,Yea,0.610577,0,210,Nay,1.000000,0.610577
212,1st,213,21-Jul-2025,H R 3095,"On Motion to Suspend the Rules and Pass, as Am...",To direct the United States Postal Service to ...,278,121,203,0,Yea,1.000000,75,121,Nay,0.617347,0.617347
606,2nd,245,15-Jul-2026,H R 8595,On Agreeing to the Amendment,NaN,136,291,136,80,Yea,0.629630,0,210,Nay,1.000000,0.629630
433,2nd,72,24-Feb-2026,S 2503,On Motion to Suspend the Rules and Pass,ROTOR Act,264,133,77,132,Nay,0.631579,187,1,Yea,0.994681,0.631579
198,1st,199,17-Jul-2025,H R 3633,On Passage,CLARITY Act,294,134,216,0,Yea,1.000000,78,134,Nay,0.632075,0.632075
70,1st,71,11-Mar-2025,H J RES 25,On Passage,Providing for congressional disapproval under ...,292,132,216,0,Yea,1.000000,76,132,Nay,0.634615,0.634615
405,2nd,44,22-Jan-2026,H R 7148,On Agreeing to the Amendment,NaN,136,291,136,76,Yea,0.641509,0,215,Nay,1.000000,0.641509
229,1st,230,3-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,140,286,140,78,Yea,0.642202,0,208,Nay,1.000000,0.642202
509,2nd,148,30-Apr-2026,H R 7567,On Agreeing to the Amendment,NaN,280,142,73,135,Nay,0.649038,207,6,Yea,0.971831,0.649038
227,1st,228,3-Sep-2025,H R 4553,On Agreeing to the Amendment,NaN,143,285,143,73,Yea,0.662037,0,212,Nay,1.000000,0.662037
24,1st,25,23-Jan-2025,H R 471,On Passage,Fix Our Forests Act,279,141,215,0,Yea,1.000000,64,141,Nay,0.687805,0.687805
16,1st,17,16-Jan-2025,H R 30,On Passage,Preventing Violence Against Women by Illegal A...,274,145,213,0,Yea,1.000000,61,145,Nay,0.703883,0.703883
310,1st,311,3-Dec-2025,H R 4305,On Passage,DUMP Red Tape Act,269,146,210,0,Yea,1.000000,59,146,Nay,0.712195,0.712195
373,2nd,12,9-Jan-2026,H R 5184,On Passage,Affordable HOMES Act,263,147,206,0,Yea,1.000000,57,147,Nay,0.720588,0.720588

In [25]:
weakest.shape

(30, 17)

In [26]:
opposed_rolls["party_separation"] = (
    opposed_rolls["republican_yea_share_of_yea_nay"] -
    opposed_rolls["democratic_yea_share_of_yea_nay"]
).abs()

opposed_rolls[[
    "session",
    "roll_number",
    "vote_description",
    "republican_yea_share_of_yea_nay",
    "democratic_yea_share_of_yea_nay",
    "party_separation",
]].sort_values("party_separation").head(30)

,session,roll_number,vote_description,republican_yea_share_of_yea_nay,democratic_yea_share_of_yea_nay,party_separation
525,2nd,164,Nationwide Consumer and Fuel Retailer Choice Act,0.575472,0.456731,0.118741
619,2nd,258,NaN,0.422535,0.825472,0.402936
199,1st,200,GENIUS Act,0.944954,0.481132,0.463822
604,2nd,243,NaN,0.004630,0.512438,0.507808
32,1st,33,HALT Fentanyl Act,0.995349,0.478049,0.517300
304,1st,305,Denouncing the horrors of socialism,1.000000,0.467391,0.532609
532,2nd,171,Cashless Bail Reporting Act,0.990610,0.457143,0.533467
233,1st,234,NaN,0.555556,0.000000,0.555556
230,1st,231,NaN,0.555556,0.000000,0.555556
234,1st,235,NaN,0.558140,0.000000,0.558140
231,1st,232,NaN,0.574074,0.000000,0.574074
327,1st,328,Increasing Investor Opportunities Act,1.000000,0.414286,0.585714
235,1st,236,NaN,0.590698,0.000000,0.590698
232,1st,233,NaN,0.590698,0.000000,0.590698
157,1st,158,Denouncing the antisemitic terrorist attack in...,1.000000,0.398936,0.601064
512,2nd,151,NaN,0.739336,0.136792,0.602544
67,1st,68,Pandemic Unemployment Fraud Enforcement Act,1.000000,0.395238,0.604762
388,2nd,27,NaN,0.610577,0.000000,0.610577
212,1st,213,To direct the United States Postal Service to ...,1.000000,0.382653,0.617347
509,2nd,148,NaN,0.350962,0.971831,0.620869
433,2nd,72,ROTOR Act,0.368421,0.994681,0.626260
606,2nd,245,NaN,0.629630,0.000000,0.629630
198,1st,199,CLARITY Act,1.000000,0.367925,0.632075
70,1st,71,Providing for congressional disapproval under ...,1.000000,0.365385,0.634615
505,2nd,144,NaN,0.811321,0.173709,0.637612
405,2nd,44,NaN,0.641509,0.000000,0.641509
229,1st,230,NaN,0.642202,0.000000,0.642202
227,1st,228,NaN,0.662037,0.000000,0.662037
24,1st,25,Fix Our Forests Act,1.000000,0.312195,0.687805
669,2nd,308,An Act to amend the Internal Revenue Code of 1...,0.966667,0.276190,0.690476

In [27]:
standard = rolls[
    rolls["validation_type"] == "party_totals"
].copy()

standard["party_separation"] = (
    standard["republican_yea_share_of_yea_nay"] -
    standard["democratic_yea_share_of_yea_nay"]
).abs()

standard["party_separation"].describe(
    percentiles=[.05, .10, .25, .50, .75, .90, .95]
)

count    673.000000
mean       0.688379
std        0.400149
min        0.000000
5%         0.000000
10%        0.015500
25%        0.271429
50%        0.953398
75%        0.995392
90%        1.000000
95%        1.000000
max        1.000000
Name: party_separation, dtype: float64

In [28]:
pd.cut(
    standard["party_separation"],
    bins=[0, .10, .20, .30, .40, .50, .60, .70, .80, .90, 1.000001],
    right=False
).value_counts().sort_index()

party_separation
[0.0, 0.1)    134
[0.1, 0.2)     22
[0.2, 0.3)     21
[0.3, 0.4)     20
[0.4, 0.5)      8
[0.5, 0.6)     11
[0.6, 0.7)     17
[0.7, 0.8)     15
[0.8, 0.9)     38
[0.9, 1.0)    387
Name: count, dtype: int64

In [29]:
standard["house_margin_share"] = (
    standard["house_yea_share_of_yea_nay"] - 0.5
).abs() * 2

standard[[
    "session",
    "roll_number",
    "vote_description",
    "house_yea",
    "house_nay",
    "house_yea_share_of_yea_nay",
    "party_separation",
    "house_margin_share",
]].sort_values(
    ["party_separation", "house_margin_share"],
    ascending=[False, True]
).head(30)

,session,roll_number,vote_description,house_yea,house_nay,house_yea_share_of_yea_nay,party_separation,house_margin_share
548,2nd,187,Smithsonian American Women’s History Museum Act,209,209,0.500000,1.0,0.000000
424,2nd,63,Securing America’s Critical Minerals Supply Act,214,215,0.498834,1.0,0.002331
402,2nd,41,Providing for consideration of the bill (H.R. ...,214,213,0.501171,1.0,0.002342
185,1st,186,Providing for consideration of the Senate amen...,212,211,0.501182,1.0,0.002364
472,2nd,111,Providing for consideration of the bills (H.R....,212,211,0.501182,1.0,0.002364
193,1st,194,Providing for consideration of the bills (H.R....,211,210,0.501188,1.0,0.002375
483,2nd,122,Providing for consideration of the bill (H.R. ...,211,210,0.501188,1.0,0.002375
544,2nd,183,PROTECT Kids Act,207,208,0.498795,1.0,0.002410
547,2nd,186,Providing for consideration of the bill (H.R. ...,208,207,0.501205,1.0,0.002410
555,2nd,194,Providing for consideration of the bills (H.R....,208,207,0.501205,1.0,0.002410
377,2nd,16,Providing for consideration of (H.R. 2988) Pro...,206,205,0.501217,1.0,0.002433
342,1st,343,Providing for consideration of the bills (H.R....,204,203,0.501229,1.0,0.002457
491,2nd,130,Providing for consideration of the bill H.R. 4...,180,179,0.501393,1.0,0.002786
420,2nd,59,Providing for consideration of the bill (H.R. ...,216,214,0.502326,1.0,0.004651
422,2nd,61,Providing for consideration of the bills (S. 1...,216,214,0.502326,1.0,0.004651
427,2nd,66,Undersea Cable Protection Act,214,216,0.497674,1.0,0.004651
476,2nd,115,FENCES Act,213,215,0.497664,1.0,0.004673
85,1st,86,Providing for consideration of the joint resol...,215,213,0.502336,1.0,0.004673
400,2nd,39,Providing for consideration of the bill (H.R. ...,215,213,0.502336,1.0,0.004673
186,1st,187,Providing for consideration of the Senate amen...,214,212,0.502347,1.0,0.004695
364,2nd,3,Providing for consideration of the bill (H.R. ...,214,212,0.502347,1.0,0.004695
473,2nd,112,Providing for consideration of the bills (H.R....,214,212,0.502347,1.0,0.004695
575,2nd,214,Secure America Act,214,212,0.502347,1.0,0.004695
90,1st,91,Providing for consideration of the joint resol...,213,211,0.502358,1.0,0.004717
140,1st,141,Providing for consideration of the bill (H.R. ...,213,211,0.502358,1.0,0.004717
363,2nd,2,Providing for consideration of the bill (H.R. ...,213,211,0.502358,1.0,0.004717
572,2nd,211,Providing for consideration of the bills H.R. ...,213,211,0.502358,1.0,0.004717
137,1st,138,NaN,211,213,0.497642,1.0,0.004717
395,2nd,34,Providing for consideration of the bills H.R. ...,212,210,0.502370,1.0,0.004739
459,2nd,98,Providing for consideration of (H.R. 8029) Pay...,212,210,0.502370,1.0,0.004739